// GENERATED by tool/gen_chord_shapes.dart - DO NOT EDIT BY HAND.
//
// The ordered chord-quality catalog (family, tier, label) used by
// the chord picker. Source: chords-db master table in the generator.
library;

import 'chord_catalog.dart';

const List<ChordQuality> kChordQualities = [
  ChordQuality(suffix: '', family: ChordFamily.major, label: 'Major', extended: false),
  ChordQuality(suffix: 'maj7', family: ChordFamily.major, label: 'maj7', extended: false),
  ChordQuality(suffix: '6', family: ChordFamily.major, label: '6', extended: false),
  ChordQuality(suffix: 'add9', family: ChordFamily.major, label: 'add9', extended: false),
  ChordQuality(suffix: 'maj9', family: ChordFamily.major, label: 'maj9', extended: true),
  ChordQuality(suffix: 'maj11', family: ChordFamily.major, label: 'maj11', extended: true),
  ChordQuality(suffix: 'maj13', family: ChordFamily.major, label: 'maj13', extended: true),
  ChordQuality(suffix: '69', family: ChordFamily.major, label: '6/9', extended: true),
  ChordQuality(suffix: 'm', family: ChordFamily.minor, label: 'Minor', extended: false),
  ChordQuality(suffix: 'm7', family: ChordFamily.minor, label: 'm7', extended: false),
  ChordQuality(suffix: 'm6', family: ChordFamily.minor, label: 'm6', extended: false),
  ChordQuality(suffix: 'madd9', family: ChordFamily.minor, label: 'madd9', extended: false),
  ChordQuality(suffix: 'm9', family: ChordFamily.minor, label: 'm9', extended: true),
  ChordQuality(suffix: 'm11', family: ChordFamily.minor, label: 'm11', extended: true),
  ChordQuality(suffix: 'mmaj7', family: ChordFamily.minor, label: 'mMaj7', extended: true),
  ChordQuality(suffix: '7', family: ChordFamily.dominant, label: '7', extended: false),
  ChordQuality(suffix: '9', family: ChordFamily.dominant, label: '9', extended: false),
  ChordQuality(suffix: '11', family: ChordFamily.dominant, label: '11', extended: false),
  ChordQuality(suffix: '13', family: ChordFamily.dominant, label: '13', extended: false),
  ChordQuality(suffix: '7b5', family: ChordFamily.dominant, label: '7b5', extended: true),
  ChordQuality(suffix: '7b9', family: ChordFamily.dominant, label: '7b9', extended: true),
  ChordQuality(suffix: '7#9', family: ChordFamily.dominant, label: '7#9', extended: true),
  ChordQuality(suffix: '9b5', family: ChordFamily.dominant, label: '9b5', extended: true),
  ChordQuality(suffix: '7sus4', family: ChordFamily.dominant, label: '7sus4', extended: true),
  ChordQuality(suffix: 'sus2', family: ChordFamily.suspended, label: 'sus2', extended: false),
  ChordQuality(suffix: 'sus4', family: ChordFamily.suspended, label: 'sus4', extended: false),
  ChordQuality(suffix: 'dim', family: ChordFamily.diminished, label: 'dim', extended: false),
  ChordQuality(suffix: 'dim7', family: ChordFamily.diminished, label: 'dim7', extended: false),
  ChordQuality(suffix: 'm7b5', family: ChordFamily.diminished, label: 'm7b5', extended: false),
  ChordQuality(suffix: 'aug', family: ChordFamily.augmented, label: 'aug', extended: false),
  ChordQuality(suffix: 'aug7', family: ChordFamily.augmented, label: 'aug7', extended: false),
  ChordQuality(suffix: 'aug9', family: ChordFamily.augmented, label: 'aug9', extended: true),
];
